repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
  - repo: https://github.com/psf/black
    rev: 25.1.0
    hooks:
      - id: black
        language_version: python3
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: "v0.12.10"
    hooks:
      - id: ruff
  - repo: https://github.com/PyCQA/flake8
    rev: 7.3.0
    hooks:
      - id: flake8
  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        name: isort (python)

  # Hook per djlint cross-platform
  - repo: local
    hooks:
      - id: djlint-cross-platform
        name: Format Django HTML templates
        entry: uv run djlint src/templates/ --reformat --ignore H030
        language: python
        additional_dependencies: [djlint]
        pass_filenames: false
        files: \.html$
        always_run: true

  # Hook per pylint cross-platform
  - repo: local
    hooks:
      - id: pylint-cross-platform
        name: pylint
        entry: python -c "import os; os.environ['PYTHONPATH'] = './src' + os.pathsep + os.environ.get('PYTHONPATH', ''); import sys; from pylint import lint; lint.Run(['-rn', '-sn', '--load-plugins=pylint_django', '--django-settings-module=home.settings'] + sys.argv[1:])"
        language: python
        additional_dependencies: [pylint, pylint-django]
        types: [python]
        require_serial: true
        exclude: examples/.*

  # Markdown formatter using Prettier
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v4.0.0-alpha.8
    hooks:
      - id: prettier
        name: prettier (markdown)
        types: [markdown]
        additional_dependencies:
          - prettier@3.2.5

  # Markdown linting
  - repo: https://github.com/DavidAnson/markdownlint-cli2
    rev: v0.12.1
    hooks:
      - id: markdownlint-cli2
        name: markdownlint
        types: [markdown]
