

repos:
  # Controlli di base
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
        exclude: |
          (?x)(^node_modules/.*|^dist/.*|^build/.*|^out/.*|^\.venv/.*|^venv/.*|^__pycache__/.*|^.*\.egg-info/.*|(^|/)migrations/.*|.*\.tmp$|.*\.temp$|\.secrets$|^\.pytest_cache/.*)
      - id: end-of-file-fixer
        exclude: |
          (?x)(^node_modules/.*|^dist/.*|^build/.*|^out/.*|^\.venv/.*|^venv/.*|^__pycache__/.*|^.*\.egg-info/.*|(^|/)migrations/.*|.*\.tmp$|.*\.temp$|\.secrets$|^\.pytest_cache/.*)
      - id: check-yaml
        exclude: |
          (?x)(^node_modules/.*|^dist/.*|^build/.*|^out/.*|^\.venv/.*|^venv/.*|^__pycache__/.*|^.*\.egg-info/.*|(^|/)migrations/.*|.*\.tmp$|.*\.temp$|\.secrets$|^\.pytest_cache/.*)
      - id: check-added-large-files
        exclude: |
          (?x)(^node_modules/.*|^dist/.*|^build/.*|^out/.*|^\.venv/.*|^venv/.*|^__pycache__/.*|^.*\.egg-info/.*|(^|/)migrations/.*|.*\.tmp$|.*\.temp$|\.secrets$|^\.pytest_cache/.*)

  # Formattazione del codice
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: "v0.12.10"
    hooks:
      - id: ruff-format
        name: ruff (formatter)
        exclude: |
          (?x)(^node_modules/.*|^dist/.*|^build/.*|^out/.*|^\.venv/.*|^venv/.*|^__pycache__/.*|^.*\.egg-info/.*|(^|/)migrations/.*|.*\.tmp$|.*\.temp$|\.secrets$|^\.pytest_cache/.*)
      - id: ruff
        name: ruff (linter)
        args: [--fix]
        exclude: |
          (?x)(^node_modules/.*|^dist/.*|^build/.*|^out/.*|^\.venv/.*|^venv/.*|^__pycache__/.*|^.*\.egg-info/.*|(^|/)migrations/.*|.*\.tmp$|.*\.temp$|\.secrets$|^\.pytest_cache/.*)

  # Linting più specifico
  - repo: https://github.com/PyCQA/flake8
    rev: 7.3.0
    hooks:
      - id: flake8
        args: ["--config=.config/flake8"]
        exclude: |
          (?x)(^node_modules/.*|^dist/.*|^build/.*|^out/.*|^\.venv/.*|^venv/.*|^__pycache__/.*|^.*\.egg-info/.*|(^|/)migrations/.*|.*\.tmp$|.*\.temp$|\.secrets$|^\.pytest_cache/.*)

  # Hook per djlint cross-platform
  - repo: https://github.com/Riverside-Healthcare/djlint
    rev: v1.36.4
    hooks:
      - id: djlint
        name: Format Django HTML templates
        files: \.(html|jinja|j2)$
        additional_dependencies: [djlint==1.36.4]
        exclude: |
          (?x)(^node_modules/.*|^dist/.*|^build/.*|^out/.*|^\.venv/.*|^venv/.*|^__pycache__/.*|^.*\.egg-info/.*|(^|/)migrations/.*|.*\.tmp$|.*\.temp$|\.secrets$|^\.pytest_cache/.*)

  # Hook unificato per pylint che funziona su tutte le piattaforme
  - repo: local
    hooks:
      - id: pylint-unified
        name: pylint
        language: python
        entry: python scripts/run_pylint.py
        types: [python]
        require_serial: true
        stages: [pre-commit]
        pass_filenames: false
        additional_dependencies: [pylint, pylint-django]
        exclude: |
          (?x)(^node_modules/.*|^dist/.*|^build/.*|^out/.*|^\.venv/.*|^venv/.*|^__pycache__/.*|^.*\.egg-info/.*|(^|/)migrations/.*|.*\.tmp$|.*\.temp$|\.secrets$|^\.pytest_cache/.*|tools/add_docstring.py)

  # Versione Unix (solo per GitHub Actions)
  - repo: local
    hooks:
      - id: pylint-unix-ci
        name: pylint (CI)
        language: python
        entry: python scripts/run_pylint.py
        types: [python]
        require_serial: true
        stages: [pre-commit]
        pass_filenames: false
        additional_dependencies: [pylint, pylint-django]
        exclude: |
          (?x)(^node_modules/.*|^dist/.*|^build/.*|^out/.*|^\.venv/.*|^venv/.*|^__pycache__/.*|^.*\.egg-info/.*|(^|/)migrations/.*|.*\.tmp$|.*\.temp$|\.secrets$|^\.pytest_cache/.*|tools/add_docstring.py)

  # Markdown formatter using Prettier
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v4.0.0-alpha.8
    hooks:
      - id: prettier
        name: prettier (markdown)
        types: [markdown]
        args: ["--config", ".config/prettierrc.json"]
        additional_dependencies:
          - prettier@3.2.5
        exclude: |
          (?x)(^node_modules/.*|^dist/.*|^build/.*|^out/.*|^\.venv/.*|^venv/.*|^__pycache__/.*|^.*\.egg-info/.*|(^|/)migrations/.*|.*\.tmp$|.*\.temp$|\.secrets$|^\.pytest_cache/.*)

  # Markdown linting
  - repo: https://github.com/DavidAnson/markdownlint-cli2
    rev: v0.18.1
    hooks:
      - id: markdownlint-cli2
        name: markdownlint
        types: [markdown]
        args: ["--config", ".config/.markdownlint-cli2.jsonc"]
        exclude: |
          (?x)(^node_modules/.*|^dist/.*|^build/.*|^out/.*|^\.venv/.*|^venv/.*|^__pycache__/.*|^.*\.egg-info/.*|(^|/)migrations/.*|.*\.tmp$|.*\.temp$|\.secrets$|^\.pytest_cache/.*)
