repos:
  # Controlli di base
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files

  # Formattazione del codice
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: "v0.12.10"
    hooks:
      - id: ruff-format
        name: ruff (formatter)
      - id: ruff
        name: ruff (linter)

  # Linting più specifico
  - repo: https://github.com/PyCQA/flake8
    rev: 7.3.0
    hooks:
      - id: flake8
        args: ["--config=.config/flake8"]

  # Hook per djlint cross-platform
  - repo: local
    hooks:
      - id: djlint-cross-platform
        name: Format Django HTML templates
        entry: python scripts/run_djlint.py
        language: python
        additional_dependencies: [djlint]
        pass_filenames: false
        files: \.html$
        always_run: true

  # Hook unificato per pylint che funziona su tutte le piattaforme
  - repo: local
    hooks:
      - id: pylint-unified
        name: pylint
        language: python
        entry: python scripts/run_pylint.py
        types: [python]
        require_serial: true
        stages: [pre-commit]
        pass_filenames: false
        additional_dependencies: [pylint, pylint-django]

  # Versione Unix (solo per GitHub Actions)
  - repo: local
    hooks:
      - id: pylint-unix-ci
        name: pylint (CI)
        language: python
        entry: python scripts/run_pylint.py
        types: [python]
        require_serial: true
        stages: [pre-commit]
        pass_filenames: false
        additional_dependencies: [pylint, pylint-django]

  # Markdown formatter using Prettier
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v4.0.0-alpha.8
    hooks:
      - id: prettier
        name: prettier (markdown)
        types: [markdown]
        args: ["--config", ".config/prettierrc.json"]
        additional_dependencies:
          - prettier@3.2.5

  # Markdown linting
  - repo: https://github.com/DavidAnson/markdownlint-cli2
    rev: v0.18.1
    hooks:
      - id: markdownlint-cli2
        name: markdownlint
        types: [markdown]
