[project]
name = "deploy-django"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "django===5.2.0",
]

[tool.flake8]
max-line-length = 120

[tool.black]
line-length = 120
